### ISSUE TITLE
Remove svn structure

### ISSUE THREAD

**Issue by jmcejuela** [Rostlab/SNAP2#2]
I saw you already started the branch `clean_svn_remains` :-)

So yes, this issue is about removing the svn structure (`trunk/`, `tags/`) and so on.

For this and to make it clean, **it may be necessary to recreate the repository**. If so, please let me know

**Comment by seitza** [comment]
I finished the cleanup and indeed it was necessary to create a new (still local) repository. I messed the current one up. Could you please recreate it, so we can start with a clean one again (since we're lacking the user rights)? I already saved all our progress locally, so you can just kill it on github and create a new one. Thanks.

**Comment by jmcejuela** [comment]
Thank you. Doing now. 

(This comment will be deleted ;-)
